### PR TITLE
Add repository field

### PR DESCRIPTION
**Pull request by felixfbecker**
Global references rely on this field

### CODE REVIEW

**Comment by felixfbecker** [comment]
PTAL @chrismwendt, I don't have push permissions to this repo

**Comment by chrismwendt** [comment]
Oh shoot, I didn't have email notifications set up for this repo until now.

I added the repository field a few days ago, so I'll close this.

**Comment by felixfbecker** [comment]
No worries, could you give admin access to all teammates?

**Comment by chrismwendt** [comment]
Yup, done!

**Pull request closed without merging**
